server:
  port: 12000
  servlet:
    context-path: /api/v1/
logging:
  level:
    .: info
    cn.lhfei.drill: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# Druid datasource settings:
spring:
  profiles:
    active:
    - dev
  datasource:
    driver-class-name: org.apache.drill.jdbc.Driver
    url:  host-10-182-60-8:2181,host-10-182-60-113:2181,host-10-182-60-142:2181,host-10-182-60-149:2181/drill/drillbits-li
    username: 
    password: 
