server:
  port: 12000
  servlet:
    context-path: /api/v1/
logging:
  level:
    .: info
    cn.lhfei.drill: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# Druid datasource settings:
spring:
  profiles:
    active:
    - dev
  datasource:
    driver-class-name: org.apache.drill.jdbc.Driver
    url:  jdbc:drill:zk=a01-r03-i164-107-515wbkc.jd.local:2181,a01-r03-i164-101-515w96w.jd.local:2181,a01-r03-i164-108-515wble.jd.local:2181/drill/DTHINKER-BITS
    username: 
    password: 
