server:
  port: 12000
  servlet:
    context-path: /api/v1/
logging:
  level:
    .: info
    cn.lhfei.drill: debug
    org.springframework: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


# Druid datasource settings:
spring:
  datasource:
    driver-class-name: org.apache.drill.jdbc.Driver
    url:  jdbc:drill:zk:a01-r03-i164-107-515wbkc.jd.local:2181,a01-r03-i164-101-515w96w.jd.local:2181,a01-r03-i164-108-515wble.jd.local:2181/drill/DTHINKER-BITS
    username: 
    password: 

    druid:
      initial-size: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql:true;druid.stat.slowSqlMillis:5000
      #useGlobalDataSourceStat: true